
##################
# Custom Theme & Appearance
##################
theme = "night_owl"


##################
# Editor behaviour
##################
[editor]
line-number         = "relative"
default-line-ending = "lf"
mouse               = true
cursorline          = true
color-modes         = true
true-color          = true
auto-pairs          = false
scrolloff           = 6
bufferline          = "multiple"
continue-comments   = false


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "â”Š"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "version-control", "register", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "Nor"
mode.insert = "Ins"
mode.select = "Sel"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.inline-diagnostics]
cursor-line = "hint"

##################
# Key Bindings
##################

[keys.normal]
"Meta-p" = "command_palette"
"Meta-l" = ":toggle line-number absolute relative"
"C-s"    = ":write"
"C-n"    = ":new"
"%"      = "match_brackets"
H        = ":buffer-previous"
L        = ":buffer-next"
X        = "select_line_above"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.g]
G     = "goto_file_end"

[keys.select]
ret = "extend_to_word"
X = "select_line_above"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.insert]
"Meta-p" = "command_palette"
"Meta-l" = ":toggle line-number absolute relative"
"C-s"    = ":write"

[keys.normal.backspace]
M = ":run-shell-command make"
w = ":write-all"
r = [":reload-all", ":config-reload"]
# Yazi
e = [
  ':sh rm -f /tmp/yazi-hx-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-hx-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/yazi-hx-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
# Lazygit
g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]


